name: Build and Deploy package

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Unit testing
        run: dotnet test

      - name: Create package
        run: dotnet pack --configuration Release
      
      - name: Publish
        run: dotnet nuget push "MyCustomPackages_Mateusbnl/bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/Mateusbnl/index.json --skip-duplicate